### ISSUE TITLE
`mavenCompatible` option is ignored

### ISSUE THREAD

**Issue by stephanh** [typesafehub/dbuild#157]
When setting repo urls to be `mavenCompatible` the keyword seems to be ignored. 

Sample setting:
`artifactory: http://host/artifactory/repo/, [organization]/[module]_[scalaVersion]_[sbtVersion]/[revision]/[artifact](-[classifier])-[revision].[ext], mavenCompatible`

It tries to resolve the url:
`http://host/artifactory/omnia/au.com.org/dependency_2.10_0.13/0.5.1-20141203050148-04177e4/ivy-0.5.1-20141203050148-04177e4.xml`

instead of 

`http://host/artifactory/omnia/au/com/org/dependency_2.10_0.13/0.5.1-20141203050148-04177e4/ivy-0.5.1-20141203050148-04177e4.xml`

**Comment by jsuereth** [comment]
I think you want to use `[orgPath]` instead of `[organization]`.  

Reference:

    [orgPath] (since 2.3)
    the organisation name where '.' has been replaced by '/'. This can be used to configure maven2-like     repositories.

http://ant.apache.org/ivy/history/latest-milestone/concept.html

**Comment by cunei** [comment]
@stephanh, I am closing this ticket as there has not been any activity in 30 days. Please feel free to reopen, or to open a new ticket, in case the answer did not solve your issue,or if this issue needs to be explored further.
