### ISSUE TITLE
deploy to remote maven repo over http

### ISSUE THREAD

**Issue by adriaanm** [typesafehub/dbuild#163]
... not working in 0.9.2 or 0.9.3-M2, with the most recent failure being due to 

https://github.com/typesafehub/dbuild/commit/6f88f36063278113e0560f92dcd04253f723ec78#commitcomment-10879893

On 0.9.2 I hit the sys.error on https://github.com/typesafehub/dbuild/blob/v0.9.2/deploy/src/main/scala/com/typesafe/dbuild/deploy/Deploy.scala#L150

**Comment by cunei** [comment]
Hi @adriaanm, I am looking into this now.

**Comment by adriaanm** [comment]
Thanks for the update -- I should clarify this is not a blocker, so feel free to delay this.

**Comment by adriaanm** [comment]
@cunei, could I ask you to instead share any caveats (if any) you can think of in configuring dbuild (for the IDE build) to use artifactory as a maven caching proxy (set up local to the scala-ci jenkins cluster) over at https://github.com/scala/scala-jenkins-infra/issues/13? Thanks!
