### ISSUE TITLE
Support for removed modules in Scala 2.12

### ISSUE THREAD

**Issue by lrytz** [typesafehub/dbuild#164]
In Scala 2.12:

  - The Scala project no longer depends on the `scala-actors-migration`, `scala-continuations-plugin` and `scala-continuations-library` modules
  - The Scala project no longer builds the `scala-actors` module

This is implemented in this PR: https://github.com/scala/scala/pull/4466

Running a community build on that PR fails (https://jenkins-dbuild.typesafe.com:8499/job/Community-2.11.x-manual/163/consoleFull):
```
[scala:error] java.lang.RuntimeException: Cannot find artifacts dir for: org.scala-lang#scala-actors
```

[ScalaBuildSystem.scala](https://github.com/typesafehub/dbuild/blob/master/support/src/main/scala/com/typesafe/dbuild/support/scala/ScalaBuildSystem.scala) needs to be updated. @cunei, could you take a look?

**Comment by jsuereth** [comment]
@lrytz We're still taking care of the bintray migration.  Which means, I'd estimate ~ 7 days before we can get to this.  If you have time to make the PRs to bintray, we can help guide a litlte bit, but we're a bit swamped right now.  I don't want to delay 2.12.0-M1, but I think that's what you may have to do here.

**Comment by cunei** [comment]
I've done some debugging: dbuild is not at fault here. In the root of the Scala source tree there is a file called "dbuild-meta.json". When using the ant build script, dbuild is unable to extract automatically the dependencies of the Scala compiler and the list of generated artifacts; the file "dbuild-meta.json", therefore, is used to provide this information to dbuild. The file must be kept in sync with the ant build file, however. I submitted a pull request against the 2.12.x branch: https://github.com/scala/scala/pull/4507
