### ISSUE TITLE
Resolver.jcenterRepo unknown in dbuild

### ISSUE THREAD

**Issue by cunei** [typesafehub/dbuild#168]
The repository specification "Resolver.jcenterRepo" does not resolve correctly in dbuild.
See https://github.com/scala/community-builds/issues/99 for details.

**Comment by jsuereth** [comment]
I think you just need to bump to the latest sbt for that.

**Comment by ktoso** [comment]
Correct, it's available since 0.13.5+ (inclusive).

**Comment by SethTisue** [comment]
@cunei looks like this issue can be closed then?

**Comment by cunei** [comment]
Closing
