### ISSUE TITLE
Remove references to ant in ScalaBuildSystem

### ISSUE THREAD

**Issue by dwijnand** [typesafehub/dbuild#185]
With Scala's build now officially sbt, the ant build will be removed (see https://github.com/scala/scala/pull/5311).

So ScalaBuildSystem shouldn't depend on the existence of Ant (or should it be parameterised? or should it all be removed?).

Anyways these were the references I found:

* https://github.com/typesafehub/dbuild/blob/v0.9.5/support/src/main/scala/com/typesafe/dbuild/support/scala/ScalaBuildSystem.scala#L208
* https://github.com/typesafehub/dbuild/blob/v0.9.5/support/src/main/scala/com/typesafe/dbuild/support/scala/ScalaBuildSystem.scala#L376

**Comment by SethTisue** [comment]
I'd suggesting leaving it in place for as long as the 2.11.x community build continues to exist, which will be a while yet. (If it becomes a maintenance burden, the 2.11.x community build could be frozen at the last dbuild version that supported it.)

There's no need to update it for 2.12.x; in a 2.12.x context we'll simply stop using it, as per https://github.com/scala/community-builds/issues/274

**Comment by dwijnand** [comment]
Yes, I came to learn much later that the intent was to not build the Scala project at all in dbuild.

So that makes this ticket a cleanup ticket rather than a bug fix ticket.
