### ISSUE TITLE
dbuild uses `name` in duplicates checking, should be `moduleName`

### ISSUE THREAD

**Issue by SethTisue** [typesafehub/dbuild#188]
this came up in the community build, where I couldn't build Cats because dbuild complained that both Cats and macro-compat produced `org.typelevel#core` (which they don't)

details at https://github.com/typelevel/cats/issues/1396 (I had initially thought the problem was on the Cats side)

**Comment by dwijnand** [comment]
Perhaps instead of `moduleName` it should be whatever becomes the `artifactId` in the POM.

This would allow, as an example, dbuild to not fail when seeing both a cats-core for JVM and a cats-core for JS, by seeing them as `org.typelevel#cats-core_2.11` and `org.typelevel#cats-core_sjs0.6_2.11`.

**Comment by SethTisue** [comment]
I opened a separate ticket (#193) on the Scala.js angle here.

**Comment by cunei** [comment]
@SethTisue The duplicate checking is technically done, according to the suggestion, so this issue should be solved. I spoke with @dwijnand concerning Scala.js, and the issue there is different (see comment in #193)
