### ISSUE TITLE
Support test:compile only without test:test

### ISSUE THREAD

**Issue by dwijnand** [typesafehub/dbuild#189]
The community build from time to time has to disable project tests for one reason or another.

It would be nice if there were an option to disable only _running_ the tests, but still compiling them.

**Comment by SethTisue** [comment]
I haven't tried it, but I think this might already be supported via `test-tasks`, actually? (https://typesafehub.github.io/dbuild/0.9.5/dbuild.html#sbt-specific-options)

or if that fails, we might well be able to find some hacky thing to put in `extra.commands` to get the same effect

**Comment by dwijnand** [comment]
Yeah looks to me like setting `test-tasks` to `test:compile` might do this.

**Comment by SethTisue** [comment]
`compile` (not `test:compile`) works. so I think we can close this ticket. (@cunei maybe a doc update before closing?)

**Comment by dwijnand** [comment]
github issue search is the new docs

**Comment by SethTisue** [comment]
lots of examples of this, now, in community.dbuild
