### ISSUE TITLE
sbt 0.13 compatibility (avoid deprecated operators)

### ISSUE THREAD

**Issue by SethTisue** [typesafehub/dbuild#190]
dbuild inserts stuff into builds that uses the `<<=` operator, which is deprecated in sbt 0.13

this causes noise in build logs:

> [mima:error] /home/jenkins/workspace/scala-2.11.x-jdk8-integrate-community-build/target-0.9.5/extraction/fd166a3742340e0d03d17622d468651861ad2ebf/projects/fe5fc9dbf0fed7d1455995b72f37ed6ce3592ebc/project/ÿÿÿÿÿÿÿÿÿÿ~~~~dbuild~defs.sbt:1: warning: `<<=` operator is deprecated. Use `key := { x.value }` or `key ~= (old => { newValue })`.

worse, if somebody has `-Xfatal-warnings` enabled for their build definition itself, it fails the build

fyi @dwijnand

**Comment by dwijnand** [comment]
@SethTisue From looking at the sources of where dbuild writes that defs.sbt file I think these are coming from the extra settings you inject:

* https://github.com/scala/community-builds/blob/2.12.x/community.dbuild#L47
* https://github.com/scala/community-builds/blob/2.11.x-jdk8/common.conf#L139
* https://github.com/scala/community-builds/blob/2.11.x/common.conf#L133
* https://github.com/scala/community-builds/blob/2.12.0/community.dbuild#L47

**Comment by SethTisue** [comment]
doh. ok, I'll fix

**Comment by SethTisue** [comment]
well, actually:

```
[acyclic:error] onLoad in Global <<= (onLoad in Global) { previousOnLoad => previousOnLoad andThen { state => { com.typesafe.dbuild.plugin.DependencyAnalysis.printCmd(state,previousOnLoad) } }}
[acyclic:error]                  ^
```

I think this one is coming from dbuild.
