### ISSUE TITLE
0.9.9 not tagged?

### ISSUE THREAD

**Issue by SethTisue** [typesafehub/dbuild#199]
I don't see it at https://github.com/typesafehub/dbuild/releases

**Comment by SethTisue** [comment]
or release notes at https://github.com/typesafehub/dbuild/blob/master/CHANGELOG.md

**Comment by cunei** [comment]
I had pushed the tag to the wrong repository; now the tag is in the main repo as well. The changelog is not up-to-date yet, I'll fix it soon.

**Comment by dwijnand** [comment]
So close to dbuild 1.0.0! :D
