### ISSUE TITLE
integrate dbuild into scala release jenkins infrastructure

### ISSUE THREAD

**Issue by adriaanm** [typesafehub/dbuild#25]
I'm working on moving our release jenkins jobs from Josh's VMs to the scala jenkins here: 
https://scala-webapps.epfl.ch/jenkins/view/scala-release/

It would be great to be able to trigger a build of akka (and whatever "external" artifacts we include in the distro) from the scala-dist jenkins job.

**Comment by SethTisue** [comment]
@adriaanm this is no longer applicable, right?

**Comment by adriaanm** [comment]
indeed
