### ISSUE TITLE
Restrict which dependency versions get replaced

### ISSUE THREAD

**Issue by pvlugter** [typesafehub/dbuild#3]
We need something like a 'provides' mechanism when rewiring dependencies.

For example, the Play project would need the scala dependency rewired for some projects (that currently depend on scala 2.10.0-M7), but not all. Some projects would stay on scala 2.9.2, due to lining up with sbt 0.12. We still want to build the latest version of the scala 2.9.2 projects as these will be depended on downstream.

**Comment by gkossakowski** [comment]
The spaces mechanism addresses the problem of targetting multiple Scala versions. I think this issue could be closed. //cc @cunei

**Comment by cunei** [comment]
Yes, indeed: Scala 2.9 can be used to compile 0.12 plugins, using a space that is distinct from that of the main projects. Full support for sbt plugins was added in dbuild 0.9.0. Closing, thanks.
